baseURL = 'https://kivyfreakt.ru/'
title = 'kivyfreakt'
theme = 'black-and-light'
author = "Никита Яловега"
canonifyurls = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[params]
  sitename = "НЯ"
  disableWebFonts = false
  homeIntroTitle = 'ня!(^o^)//'
  homeIntroContent = """
  Я ненавижу Антихайп, он сломал мою жизнь.
  """
  homePostsTitle = 'Последние тексты'
  homePostsCount = 3
  homePhotoTitle = 'Последние фото'
  math = false


[[params.social]]
  name = "github"
  url = "https://github.com/kivyfreakt"

[[params.social]]
  name = "instagram"
  url = "https://instagram.com/kivyfreakt"

[[params.social]]
  name = "telegram"
  url = "https://t.me/musicfreakt"


[[menu.main]]
  name = "посты"
  url = "/posts"

[[menu.main]]
  name = "фото"
  url = "/photos"

